module Travelport::Request
end
require 'travelport/request/base'
require 'travelport/request/low_fare_search_req'
require 'travelport/request/air_price_req'
require 'travelport/request/air_create_reservation_req'
require 'travelport/request/air_ticketing_req'
require 'travelport/request/hotel_search_availability_req'
require 'travelport/request/hotel_details_req'
require 'travelport/request/hotel_create_reservation_req'
require 'travelport/request/hotel_media_links_req'
require 'travelport/request/vehicle_search_availability_req'
require 'travelport/request/vehicle_media_links_req'
require 'travelport/request/vehicle_location_detail_req'
require 'travelport/request/vehicle_create_reservation_req'
require 'travelport/request/reference_data_retrieve_req'